name: gg_test_matchers
description: gg_test_matchers provides various additional dart test matchers
version: 1.1.0
repository: https://github.com/ggsuite/gg_test_matchers.git

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  test: ^1.25.6

dev_dependencies:
  lints: ^6.0.0
