name: gg_test_matchers
description: gg_test_matchers provides various additional dart test matchers
version: 1.0.0
repository: https://github.com/ggsuite/gg_test_matchers.git
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  path: ^1.9.0
  args: ^2.7.0
  gg_console_colors: ^2.1.5
  gg_process: ^1.1.6
  gg_args: ^2.0.4
  gg_log: ^1.0.6

dev_dependencies:
  gg_capture_print: ^1.0.9
  lints: ^6.0.0
  test: ^1.25.6

executables:
 gg_test_matchers: